apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-service-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /scans
        backend:
          serviceName: api-service
          servicePort: 3000

